rule all:
    input:
        "data/datasets/ts_4_pr.csv",
        "data/datasets/ts_6_pr.csv",
        "data/datasets/debcred_hits_yearly.jsonline",
        "data/debcred_pr_segmentation.ipynb",
        "data/debadmcred_stats.ipynb",
        "data/datasets/debadmcred_pr_yearly.jsonline"

rule debtor_creditor_network:
    output:
        nodes_tsv="data/datasets/debcred_nodes.tsv",
        edges_tsv="data/datasets/debcred_edges.tsv",
    shell:
        """
        python export_network.py --nodes_tsv {output.nodes_tsv} \
                                 --edges_tsv {output.edges_tsv} \
                                 --network_type "debtor->creditor" 
        """

rule debtor_administrator_creditor_network:
    output:
        nodes_tsv="data/datasets/debadmcred_nodes.tsv",
        edges_tsv="data/datasets/debadmcred_edges.tsv",
    shell:
        """
        python export_network.py --nodes_tsv {output.nodes_tsv} \
                                 --edges_tsv {output.edges_tsv} \
                                 --network_type "debtor->administrator->creditor" 
        """

rule debtor_creditor_network_stats:
    input:
        nodes_tsv="data/datasets/debcred_nodes.tsv",
        edges_tsv="data/datasets/debcred_edges.tsv"
    output:
        "data/debcred_stats.ipynb"
    shell:
        """
        papermill network_stats.ipynb {output} -p nodes_tsv {input.nodes_tsv} -p edges_tsv {input.edges_tsv}
        """

rule debtor_administrator_creditor_network_stats:
    input:
        nodes_tsv="data/datasets/debadmcred_nodes.tsv",
        edges_tsv="data/datasets/debadmcred_edges.tsv"
    output:
        "data/debadmcred_stats.ipynb"
    shell:
        """
        papermill network_stats.ipynb {output} -p nodes_tsv {input.nodes_tsv} -p edges_tsv {input.edges_tsv}
        """

rule calc_page_rank:
    input:
        nodes_tsv="data/datasets/debcred_nodes.tsv",
        edges_tsv="data/datasets/debcred_edges.tsv"
    output:
        "data/datasets/debcred_pr_yearly.jsonline"
    shell:
        """
        java -Xmx10000m -cp $GRAPHSLICES_EXPERIMENTS_JAR org.zviri.graphslicesexperiments.IsirPageRank \
             {input.nodes_tsv} {input.edges_tsv} {output}
        """

rule debadmcred_calc_page_rank:
    input:
        nodes_tsv="data/datasets/debadmcred_nodes.tsv",
        edges_tsv="data/datasets/debadmcred_edges.tsv"
    output:
        "data/datasets/debadmcred_pr_yearly.jsonline"
    shell:
        """
        java -Xmx15000m -cp $GRAPHSLICES_EXPERIMENTS_JAR org.zviri.graphslicesexperiments.IsirPageRank \
             {input.nodes_tsv} {input.edges_tsv} {output}
        """

rule calc_hits:
    input:
        nodes_tsv="data/datasets/debcred_nodes.tsv",
        edges_tsv="data/datasets/debcred_edges.tsv"
    output:
        "data/datasets/debcred_hits_yearly.jsonline"
    shell:
        """
        java -Xmx10000m -cp $GRAPHSLICES_EXPERIMENTS_JAR org.zviri.graphslicesexperiments.IsirHITS \
             {input.nodes_tsv} {input.edges_tsv} {output}
        """

rule dataset:
    input:
        "data/datasets/debcred_pr_yearly.jsonline"
    output:
        ts="data/datasets/ts_{window_size}_pr.csv",
        insdata="data/datasets/insdata_{window_size}_pr.csv"
    shell:
        "python prepare_dataset.py {input} {wildcards.window_size} {output.ts} {output.insdata}"

rule debcred_pr_segmentation:
    input:
        "data/datasets/debcred_pr_yearly.jsonline"
    output:
        "data/debcred_pr_segmentation.ipynb"
    shell:
        """
        papermill pr_segmentation.ipynb {output} -p graph_path {input}
        """